In [70]:
# example of a one hot encoding
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
# define data
data = asarray([['red'], ['green'], ['blue']])
print(data)
# define one hot encoding
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling
import pickle

%matplotlib inline

In [72]:
data = pd.read_csv('mushrooms.csv');
data

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,stalk-root,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,e,e,s,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,e,c,s,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,e,c,s,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,e,e,s,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,t,e,s,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,e,?,s,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,e,?,s,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,e,?,s,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,t,?,s,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,e,?,s,s,o,o,p,o,o,p,o,c,l

In [73]:
display(data)

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,stalk-root,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,e,e,s,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,e,c,s,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,e,c,s,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,e,e,s,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,t,e,s,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,e,?,s,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,e,?,s,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,e,?,s,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,t,?,s,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,e,?,s,s,o,o,p,o,o,p,o,c,l

In [74]:
data.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring    8124 non-null   object
 15  stalk-color-below-ring    8124 non-null   object
 16  veil-type                 8124 non-null   object
 17  veil-color                8124 non-null   object
 18  ring-number               8124 non-null   object
 19  ring-type                 8124 non-null   object
 20  spore-print-color         8124 non-null   object
 21  population                8124 non-null   object
 22  habitat                   8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

In [76]:
# label encoding the data 
from sklearn.preprocessing import LabelEncoder 
  
le = LabelEncoder() 
  
data['class']= le.fit_transform(data['class']) 
data['cap-shape']= le.fit_transform(data['cap-shape']) 
data['cap-surface']= le.fit_transform(data['cap-surface']) 
data['cap-color']= le.fit_transform(data['cap-color']) 
data['bruises']= le.fit_transform(data['bruises']) 
data['odor']= le.fit_transform(data['odor']) 
data['gill-attachment']= le.fit_transform(data['gill-attachment']) 
data['gill-spacing']= le.fit_transform(data['gill-spacing']) 
data['gill-size']= le.fit_transform(data['gill-size']) 
data['gill-color']= le.fit_transform(data['gill-color']) 
data['stalk-shape']= le.fit_transform(data['stalk-shape']) 
data['stalk-root']= le.fit_transform(data['stalk-root']) 
data['stalk-surface-above-ring']= le.fit_transform(data['stalk-surface-above-ring']) 
data['stalk-surface-below-ring']= le.fit_transform(data['stalk-surface-below-ring']) 
data['stalk-color-above-ring']= le.fit_transform(data['stalk-color-above-ring']) 
data['stalk-color-below-ring']= le.fit_transform(data['stalk-color-below-ring']) 
data['veil-type']= le.fit_transform(data['veil-type']) 
data['veil-color']= le.fit_transform(data['veil-color']) 
data['ring-number']= le.fit_transform(data['ring-number']) 
data['ring-type']= le.fit_transform(data['ring-type']) 
data['spore-print-color']= le.fit_transform(data['spore-print-color']) 
data['population']= le.fit_transform(data['population']) 
data['habitat']= le.fit_transform(data['habitat'])

In [77]:
data

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,stalk-root,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,0,3,2,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,0,2,2,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,0,2,2,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,0,3,2,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,1,3,2,2,7,7,0,2,1,0,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,3,2,4,0,5,0,0,0,11,0,0,2,2,5,5,0,1,1,4,0,1,2
8120,0,5,2,4,0,5,0,0,0,11,0,0,2,2,5,5,0,0,1,4,0,4,2
8121,0,2,2,4,0,5,0,0,0,5,0,0,2,2,5,5,0,1,1,4,0,1,2
8122,1,3,3,4,0,8,1,0,1,0,1,0,2,1,7,7,0,2,1,0,7,4,2
8123,0,5,2,4,0,5,0,0,0,11,0,0,2,2,5,5,0,1,1,4,4,1,2

In [78]:
data.describe()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,stalk-root,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.0,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000
mean,0.482029,3.348104,1.827671,4.504677,0.415559,4.144756,0.974151,0.161497,0.309207,4.810684,0.567208,1.109798,1.575086,1.603644,5.816347,5.794682,0.0,1.965534,1.069424,2.291974,3.596750,3.644018,1.508616
std,0.499708,1.604329,1.229873,2.545821,0.492848,2.103729,0.158695,0.368011,0.462195,3.540359,0.495493,1.061106,0.621459,0.675974,1.901747,1.907291,0.0,0.242669,0.271064,1.801672,2.382663,1.252082,1.719975
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,0.000000,3.000000,0.000000,2.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,1.000000,6.000000,6.000000,0.0,2.000000,1.000000,0.000000,2.000000,3.000000,0.000000
50%,0.000000,3.000000,2.000000,4.000000,0.000000,5.000000,1.000000,0.000000,0.000000,5.000000,1.000000,1.000000,2.000000,2.000000,7.000000,7.000000,0.0,2.000000,1.000000,2.000000,3.000000,4.000000,1.000000
75%,1.000000,5.000000,3.000000,8.000000,1.000000,5.000000,1.000000,0.000000,1.000000,7.000000,1.000000,1.000000,2.000000,2.000000,7.000000,7.000000,0.0,2.000000,1.000000,4.000000,7.000000,4.000000,2.000000
max,1.000000,5.000000,3.000000,9.000000,1.000000,8.000000,1.000000,1.000000,1.000000,11.000000,1.000000,4.000000,3.000000,3.000000,8.000000,8.000000,0.0,3.000000,2.000000,4.000000,8.000000,5.000000,6.000000

In [79]:
from sklearn.preprocessing import OneHotEncoder

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')

# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(data).toarray())
enc_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8120,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8121,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8122,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8123,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [80]:
data.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [116]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# passing bridge-types-cat column (label encoded values of bridge_types)
classes = pd.DataFrame(enc.fit_transform(data[['class']]).toarray())
classes.rename(columns = {0:'class_0', 1:'class_1'}, inplace = True) 
classes

      class_0  class_1
0         0.0      1.0
1         1.0      0.0
2         1.0      0.0
3         0.0      1.0
4         1.0      0.0
...       ...      ...
8119      1.0      0.0
8120      1.0      0.0
8121      1.0      0.0
8122      0.0      1.0
8123      1.0      0.0

[8124 rows x 2 columns]

In [117]:
cap_shape = pd.DataFrame(enc.fit_transform(data[['cap-shape']]).toarray())
cap_shape

cap_shape.rename(columns = {0:'class_0', 1:'class_1', 2:'class_2', 3:'class_3', 4:'class_4', 5:'class_5', 6:'class_6'}, inplace = True) 
cap_shape

      class_0  class_1  class_2  class_3  class_4  class_5
0         0.0      0.0      0.0      0.0      0.0      1.0
1         0.0      0.0      0.0      0.0      0.0      1.0
2         1.0      0.0      0.0      0.0      0.0      0.0
3         0.0      0.0      0.0      0.0      0.0      1.0
4         0.0      0.0      0.0      0.0      0.0      1.0
...       ...      ...      ...      ...      ...      ...
8119      0.0      0.0      0.0      1.0      0.0      0.0
8120      0.0      0.0      0.0      0.0      0.0      1.0
8121      0.0      0.0      1.0      0.0      0.0      0.0
8122      0.0      0.0      0.0      1.0      0.0      0.0
8123      0.0      0.0      0.0      0.0      0.0      1.0

[8124 rows x 6 columns]

In [89]:
cap_surface = pd.DataFrame(enc.fit_transform(data[['cap-surface']]).toarray())
cap_surface

        0    1    2    3
0     0.0  0.0  1.0  0.0
1     0.0  0.0  1.0  0.0
2     0.0  0.0  1.0  0.0
3     0.0  0.0  0.0  1.0
4     0.0  0.0  1.0  0.0
...   ...  ...  ...  ...
8119  0.0  0.0  1.0  0.0
8120  0.0  0.0  1.0  0.0
8121  0.0  0.0  1.0  0.0
8122  0.0  0.0  0.0  1.0
8123  0.0  0.0  1.0  0.0

[8124 rows x 4 columns]

In [90]:
cap_color = pd.DataFrame(enc.fit_transform(data[['cap-color']]).toarray())
cap_color

        0    1    2    3    4    5    6    7    8    9
0     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
4     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
8119  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
8120  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
8121  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
8122  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
8123  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0

[8124 rows x 10 columns]

In [91]:
bruises = pd.DataFrame(enc.fit_transform(data[['bruises']]).toarray())
bruises

        0    1
0     0.0  1.0
1     0.0  1.0
2     0.0  1.0
3     0.0  1.0
4     1.0  0.0
...   ...  ...
8119  1.0  0.0
8120  1.0  0.0
8121  1.0  0.0
8122  1.0  0.0
8123  1.0  0.0

[8124 rows x 2 columns]

In [92]:
odor = pd.DataFrame(enc.fit_transform(data[['odor']]).toarray())
odor

        0    1    2    3    4    5    6    7    8
0     0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
1     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...
8119  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8120  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8121  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8122  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
8123  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0

[8124 rows x 9 columns]

In [93]:
gill_attachment = pd.DataFrame(enc.fit_transform(data[['gill-attachment']]).toarray())
gill_attachment

        0    1
0     0.0  1.0
1     0.0  1.0
2     0.0  1.0
3     0.0  1.0
4     0.0  1.0
...   ...  ...
8119  1.0  0.0
8120  1.0  0.0
8121  1.0  0.0
8122  0.0  1.0
8123  1.0  0.0

[8124 rows x 2 columns]

In [94]:
gill_spacing = pd.DataFrame(enc.fit_transform(data[['gill-spacing']]).toarray())
gill_spacing

        0    1
0     1.0  0.0
1     1.0  0.0
2     1.0  0.0
3     1.0  0.0
4     0.0  1.0
...   ...  ...
8119  1.0  0.0
8120  1.0  0.0
8121  1.0  0.0
8122  1.0  0.0
8123  1.0  0.0

[8124 rows x 2 columns]

In [95]:
gill_size = pd.DataFrame(enc.fit_transform(data[['gill-size']]).toarray())
gill_size

        0    1
0     0.0  1.0
1     1.0  0.0
2     1.0  0.0
3     0.0  1.0
4     1.0  0.0
...   ...  ...
8119  1.0  0.0
8120  1.0  0.0
8121  1.0  0.0
8122  0.0  1.0
8123  1.0  0.0

[8124 rows x 2 columns]

In [96]:
gill_color = pd.DataFrame(enc.fit_transform(data[['gill-color']]).toarray())
gill_color

        0    1    2    3    4    5    6    7    8    9   10   11
0     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
8119  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
8120  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
8121  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
8122  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8123  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

[8124 rows x 12 columns]

In [97]:
stalk_shape = pd.DataFrame(enc.fit_transform(data[['stalk-shape']]).toarray())
stalk_shape

        0    1
0     1.0  0.0
1     1.0  0.0
2     1.0  0.0
3     1.0  0.0
4     0.0  1.0
...   ...  ...
8119  1.0  0.0
8120  1.0  0.0
8121  1.0  0.0
8122  0.0  1.0
8123  1.0  0.0

[8124 rows x 2 columns]

In [98]:
stalk_root = pd.DataFrame(enc.fit_transform(data[['stalk-root']]).toarray())
stalk_root

        0    1    2    3    4
0     0.0  0.0  0.0  1.0  0.0
1     0.0  0.0  1.0  0.0  0.0
2     0.0  0.0  1.0  0.0  0.0
3     0.0  0.0  0.0  1.0  0.0
4     0.0  0.0  0.0  1.0  0.0
...   ...  ...  ...  ...  ...
8119  1.0  0.0  0.0  0.0  0.0
8120  1.0  0.0  0.0  0.0  0.0
8121  1.0  0.0  0.0  0.0  0.0
8122  1.0  0.0  0.0  0.0  0.0
8123  1.0  0.0  0.0  0.0  0.0

[8124 rows x 5 columns]

In [99]:
stalk_surface_above_ring = pd.DataFrame(enc.fit_transform(data[['stalk-surface-above-ring']]).toarray())
stalk_surface_above_ring

        0    1    2    3
0     0.0  0.0  1.0  0.0
1     0.0  0.0  1.0  0.0
2     0.0  0.0  1.0  0.0
3     0.0  0.0  1.0  0.0
4     0.0  0.0  1.0  0.0
...   ...  ...  ...  ...
8119  0.0  0.0  1.0  0.0
8120  0.0  0.0  1.0  0.0
8121  0.0  0.0  1.0  0.0
8122  0.0  0.0  1.0  0.0
8123  0.0  0.0  1.0  0.0

[8124 rows x 4 columns]

In [100]:
stalk_surface_below_ring = pd.DataFrame(enc.fit_transform(data[['stalk-surface-below-ring']]).toarray())
stalk_surface_below_ring

        0    1    2    3
0     0.0  0.0  1.0  0.0
1     0.0  0.0  1.0  0.0
2     0.0  0.0  1.0  0.0
3     0.0  0.0  1.0  0.0
4     0.0  0.0  1.0  0.0
...   ...  ...  ...  ...
8119  0.0  0.0  1.0  0.0
8120  0.0  0.0  1.0  0.0
8121  0.0  0.0  1.0  0.0
8122  0.0  1.0  0.0  0.0
8123  0.0  0.0  1.0  0.0

[8124 rows x 4 columns]

In [101]:
stalk_color_above_ring = pd.DataFrame(enc.fit_transform(data[['stalk-color-above-ring']]).toarray())
stalk_color_above_ring

        0    1    2    3    4    5    6    7    8
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...
8119  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8120  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8121  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8122  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
8123  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0

[8124 rows x 9 columns]

In [102]:
stalk_color_below_ring = pd.DataFrame(enc.fit_transform(data[['stalk-color-below-ring']]).toarray())
stalk_color_below_ring

        0    1    2    3    4    5    6    7    8
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...
8119  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8120  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8121  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8122  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
8123  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0

[8124 rows x 9 columns]

In [103]:
veil_type = pd.DataFrame(enc.fit_transform(data[['veil-type']]).toarray())
veil_type

        0
0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
...   ...
8119  1.0
8120  1.0
8121  1.0
8122  1.0
8123  1.0

[8124 rows x 1 columns]

In [104]:
veil_color = pd.DataFrame(enc.fit_transform(data[['veil-color']]).toarray())
veil_color

        0    1    2    3
0     0.0  0.0  1.0  0.0
1     0.0  0.0  1.0  0.0
2     0.0  0.0  1.0  0.0
3     0.0  0.0  1.0  0.0
4     0.0  0.0  1.0  0.0
...   ...  ...  ...  ...
8119  0.0  1.0  0.0  0.0
8120  1.0  0.0  0.0  0.0
8121  0.0  1.0  0.0  0.0
8122  0.0  0.0  1.0  0.0
8123  0.0  1.0  0.0  0.0

[8124 rows x 4 columns]

In [105]:
ring_number = pd.DataFrame(enc.fit_transform(data[['ring-number']]).toarray())
ring_number

        0    1    2
0     0.0  1.0  0.0
1     0.0  1.0  0.0
2     0.0  1.0  0.0
3     0.0  1.0  0.0
4     0.0  1.0  0.0
...   ...  ...  ...
8119  0.0  1.0  0.0
8120  0.0  1.0  0.0
8121  0.0  1.0  0.0
8122  0.0  1.0  0.0
8123  0.0  1.0  0.0

[8124 rows x 3 columns]

In [106]:
ring_type = pd.DataFrame(enc.fit_transform(data[['ring-type']]).toarray())
ring_type

        0    1    2    3    4
0     0.0  0.0  0.0  0.0  1.0
1     0.0  0.0  0.0  0.0  1.0
2     0.0  0.0  0.0  0.0  1.0
3     0.0  0.0  0.0  0.0  1.0
4     1.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...
8119  0.0  0.0  0.0  0.0  1.0
8120  0.0  0.0  0.0  0.0  1.0
8121  0.0  0.0  0.0  0.0  1.0
8122  1.0  0.0  0.0  0.0  0.0
8123  0.0  0.0  0.0  0.0  1.0

[8124 rows x 5 columns]

In [107]:
spore_print_color = pd.DataFrame(enc.fit_transform(data[['spore-print-color']]).toarray())
spore_print_color

        0    1    2    3    4    5    6    7    8
0     0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...
8119  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8120  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8121  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8122  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
8123  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[8124 rows x 9 columns]

In [108]:
population = pd.DataFrame(enc.fit_transform(data[['population']]).toarray())
population

        0    1    2    3    4    5
0     0.0  0.0  0.0  1.0  0.0  0.0
1     0.0  0.0  1.0  0.0  0.0  0.0
2     0.0  0.0  1.0  0.0  0.0  0.0
3     0.0  0.0  0.0  1.0  0.0  0.0
4     1.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...
8119  0.0  1.0  0.0  0.0  0.0  0.0
8120  0.0  0.0  0.0  0.0  1.0  0.0
8121  0.0  1.0  0.0  0.0  0.0  0.0
8122  0.0  0.0  0.0  0.0  1.0  0.0
8123  0.0  1.0  0.0  0.0  0.0  0.0

[8124 rows x 6 columns]

In [109]:
habitat = pd.DataFrame(enc.fit_transform(data[['habitat']]).toarray())
habitat

        0    1    2    3    4    5    6
0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
1     0.0  1.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  1.0  0.0
4     0.0  1.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...
8119  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8120  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8121  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8122  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8123  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[8124 rows x 7 columns]